name: Review request
description: Things seem to work but I want comments on my solution!
title: Things seem to work but I want comments on my solution!
labels: ['review request']
body:
  - type: input
    id: repository
    attributes:
      label: Repository
      description: Paste a link to your repository.
    validations:
      required: true
  - type: checkboxes
    id: confirmation_of_accessibility
    attributes:
      label: Access rights
      description: Please confirm that your repository is public, or you have [granted access](https://docs.github.com/de/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository) to the [course supervisors](https://github.com/BMCV/mobi-fs3-python/blob/master/SUPERVISORS.md).
      options:
        - label: I hereby confirm that the supervisors can access my repository.
          required: true
  - type: input
    id: task
    attributes:
      label: Task
      description: The task number(s) for which you want comments.
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Additional context for the comments
      description: Give some context, if applicable.
    validations:
      required: false
